/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import TransactionItem from './TransactionItem';
import { TransactionData } from './types';

const transactionData: TransactionData[] = [
  {
    name: 'Paypal',
    category: 'Shopping',
    amount: 50.57,
    emoji: '🛍️',
    categoryColor: '[#D946EF]'
  },
  {
    name: 'Uber Eats',
    category: 'Eating out',
    amount: 50.57,
    emoji: '🍴',
    categoryColor: 'stone-300'
  },
  {
    name: 'Uber Eats',
    category: 'Eating out',
    amount: 50.57,
    emoji: '🍴',
    categoryColor: 'stone-300'
  },
  {
    name: 'Manhattan',
    category: 'Travel',
    amount: 50.57,
    emoji: '✈️',
    categoryColor: '[#60A5FA]',
  },
  {
    name: 'United Airlines',
    category: 'Travel',
    amount: 50.57,
    emoji: '✈️',
    categoryColor: '[#60A5FA]'
  },
  {
    name: 'Cheesecake Factory',
    category: 'Shopping',
    amount: 50.57,
    emoji: '🛍️',
    categoryColor: '[#D946EF]'
  }
];

const TransactionList: React.FC = () => {
  return (
    <section className="flex flex-col mt-3 rounded-3xl max-w-[267px]">
      {transactionData.map((transaction, index) => (
        <TransactionItem key={index} {...transaction} />
      ))}
    </section>
  );
};

export default TransactionList;