/**
 * This code was generated by Builder.io.
 */
export interface TransactionData {
  name: string;
  category: string;
  amount: number;
  emoji: string;
  categoryColor: string;
  subTransaction?: TransactionData;
}