/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface BudgetProgressProps {
  color: string;
  remaining: number;
  total: number;
}

const BudgetProgress: React.FC<BudgetProgressProps> = ({ color, remaining, total }) => {
  const filledCircles = 8 - Math.ceil((remaining / total) * 8);

  return (
    <div className="flex gap-2.5 items-start mt-6 text-sm text-white max-md:mr-2">
      {[...Array(8)].map((_, index) => (
        <div
          key={index}
          className={`flex shrink-0 w-4 h-4 rounded-full ${
            index < filledCircles ? 'bg-white bg-opacity-10' : color
          }`}
        />
      ))}
      <div className="grow shrink self-stretch w-[155px]">
        ${remaining} left in ${total} budget
      </div>
    </div>
  );
};

export default BudgetProgress;