/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const AssetSection: React.FC = () => {
  return (
    <section>
      <div data-layername="assets" className="relative mt-3 ml-3 text-base font-bold text-white">
        Assets
      </div>
      <div className="flex relative gap-10 self-end mt-2">
        <div data-layername="600000" className="text-4xl font-light text-white basis-auto">
          $600,000
        </div>
        <div className="flex gap-1.5 self-start mt-3.5 text-base font-bold text-right text-lime-300">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/bab09cafd12221ee9b3955d5eac0c10883fb331075cae7db68920963e06ccedb?placeholderIfAbsent=true&apiKey=271c6a8a64c7449c91e4662f85acfb4e" alt="" className="object-contain shrink-0 aspect-[0.68] w-[15px]" />
          <div data-layername="20">20%</div>
        </div>
      </div>
    </section>
  );
};

export default AssetSection;