/**
 * This code was generated by Builder.io.
 */
"use client"
import React, { useState } from 'react';
import Menu from './Menu';
import AssetSection from './AssetSection';
import DebtSection from './DebtSection';
import FinancialAdvisor from '../FinancialAdvisor/FinancialAdvisor';

const SideBar: React.FC = () => {
  const [isChatBoxVisible, setChatBoxVisible] = useState(false);

  const handleAdvisorClick = () => {
    setChatBoxVisible((prev) => !prev);
  };

  return (
    <div className="flex flex-col pb-9 shadow-[0px_0px_30px_rgba(0,0,0,0.3)] bg-zinc-800 max-sm:self-stretch 
    h-screen w-1/5 relative font-sans">
      <main className="flex flex-col items-start pt-3 pl-2.5 pb-2 w-full h-full max-w-[98%]">
        <div className="flex flex-row items-center justify-center">
          <img loading="lazy" src="hourglass_logo.svg" className="h-32 w-26 ml-3" alt="Hourglass Logo" />
          <div className="flex flex-col items-start">
            <p className="text-xl font-thin leading-6 font-sans text-white">Welcome to your</p>
            <h1 className="text-3xl font-semibold text-white">Hourglass</h1>
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/13b0b4dd95ede84e1f6490ebcd1d03a046cab352fc9d08a2b3e338ba42615694?placeholderIfAbsent=true&apiKey=271c6a8a64c7449c91e4662f85acfb4e"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        <div className="shrink-0 self-stretch mt-2.5 mb-2.5 h-px border border-solid border-white border-opacity-10" />
        <Menu handleAdvisorClick={handleAdvisorClick} />
        </main>
    </div>
  );
  
};

export default SideBar;