/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import InvestmentSection from './InvestmentSection';
import { InvestmentItem } from './types';

const weInvestForYouData: InvestmentItem[] = [
  { name: 'TESLA', amount: '$100,000 (250 shares at $4000)' },
  { name: 'META', amount: '$100,000 (250 shares at $4000)' },
  { name: 'Apple', amount: '$100,000 (250 shares at $4000)' },
];

const externalInvestmentsData: InvestmentItem[] = [
  { name: 'Vanguard', amount: '$10,000' },
  { name: '401K', amount: '$5000' },
];

const InvestmentDashboard: React.FC = () => {
  return (
    <main className="flex flex-col text-white rounded-none max-w-[395px]">
      <InvestmentSection
        title="We invest for you!"
        items={weInvestForYouData}
      />
      <div className="mt-6 w-full border border-solid border-white border-opacity-10 min-h-[1px]" />
      <InvestmentSection
        title="External Investments"
        items={externalInvestmentsData}
      />
    </main>
  );
};

export default InvestmentDashboard;