/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { InvestmentItem } from './types';

interface InvestmentSectionProps {
  title: string;
  items: InvestmentItem[];
}

const InvestmentSection: React.FC<InvestmentSectionProps> = ({ title, items }) => {
  return (
    <section className="flex gap-5 justify-between mt-5">
      <div className="flex flex-col items-start text-base">
        <h2 className="self-stretch font-bold text-lime-300">{title}</h2>
        {items.map((item, index) => (
          <div key={index} className={index > 0 ? "mt-4" : "mt-5"}>
            {item.name}
          </div>
        ))}
      </div>
      <div className="flex flex-col self-end mt-8 text-sm text-right">
        {items.map((item, index) => (
          <div key={index} className={index > 0 ? "mt-4" : ""}>
            {item.amount}
          </div>
        ))}
      </div>
    </section>
  );
};

export default InvestmentSection;