/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface DashboardCardProps {
  title: string;
  width: string;
}

export const DashboardCard: React.FC<DashboardCardProps> = ({ title, width }) => {
  return (
    <section className={`flex flex-col ${width} max-md:ml-0 max-md:w-full`}>
        <div className="flex flex-row justify-between grow px-8 pt-7 pb-60 w-full text-xl font-bold text-white whitespace-nowrap rounded-2xl border border-solid card-shadow bg-[#2A2E32] border-white border-opacity-30 max-md:px-5 max-md:pb-24 max-md:mt-10">
          {title}
          <img src="arrow_orange.svg"/>
        </div>
    </section>
  );
};