/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { DashboardCard } from './DashboardCard';

interface DashboardRowProps {
  cards: Array<{ title: string; width: string }>;
}

export const DashboardRow: React.FC<DashboardRowProps> = ({ cards }) => {
  return (
    <div className="mt-10 w-full max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        {cards.map((card, index) => (
          <DashboardCard key={index} title={card.title} width={card.width} />
        ))}
      </div>
    </div>
  );
};