/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import CashFlowDashboard from '../CashFlowDashboard/CashFlowDashboard';
import InvestmentDashboard from '../InvestmentDashboard/InvestmentDashboard';
import SavingsGoal from '../SavingsGoal/SavingsGoal';
import FinancialChart from '../FinancialChart/FinancialChart';
import TransactionList from '../TransactionList/TransactionList';
import { AccountSummary } from '../AccountSummary/AccountSummary';
import AssetChart from '../AssetChart/AssetChart';
import { CalendarSync } from '../CalendarSync/CalendarSync';
import LearningTrackerList from '../LearningTracker/LearningTrackerList';
import SpendingDashboard from '../SpendingDashboard/SpendingDashboard';

interface DashboardCardProps {
  title: string;
  width: string;
}

const dashboardComponents: { [key: string]: React.FC<{}> } = {
  "This Month's Budgeting": SpendingDashboard,
  "Investments": InvestmentDashboard,
  "Savings Track & Forecast": SavingsGoal,
  "Recurring Payments": FinancialChart,
  "Transactions": TransactionList,
  "Accounts": AccountSummary,
  "Projections": AssetChart,
  "Upcoming Bills": CalendarSync,
  "What You Have Learned So Far": LearningTrackerList,
}

export const DashboardCard: React.FC<DashboardCardProps> = ({ title, width }) => {
  const CardComponent = dashboardComponents[title];
  return (
    <section className={`flex flex-col w-full h-full max-md:ml-0 max-md:w-full`} >
      <div className="flex flex-col grow px-5 pt-5 pb-2 w-full text-lg font-sans font-medium text-white whitespace-nowrap rounded-2xl border border-solid bg-[#2A2E32] border-white border-opacity-30 max-md:px-5 max-md:pb-24 max-md:mt-10">
        <div className='flex flex-row justify-between'>
          {title === "What You Have Learned So Far" ? (
            <>
              What You Have <br /> Learned So Far
            </>
          ) : (
            title
          )}
          <img src="arrow_orange.svg" />
        </div>
        <div className='font-sans font-extralight'>
        {CardComponent && <CardComponent />}
        </div>
      </div>

    </section>
  );
};