/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import BudgetSummary from './BudgetSummary';
import SpendingBreakdown from './SpendingBreakdown';
import { SpendingCategory } from './types';
import useBudgetStore from './BudgetStore';

const spendingCategories: SpendingCategory[] = [
  { icon: '🛍️', name: 'Shopping', color: 'border-fuchsia-500', spent: 100, budget: 200 },
  { icon: '✈️', name: 'Travel', color: 'border-blue-400', spent: 800, budget: 1000 },
  { icon: '🍴', name: 'Eating out', color: 'border-stone-300', spent: 150, budget: 200 },
  { icon: '🍎', name: 'Groceries', color: 'border-red-500', spent: 100, budget: 200 }
];

const BudgetingDashboard: React.FC = () => {
  const budgetData = useBudgetStore((state) => state.budgetData);
  console.log("budget: "+budgetData);
  return (
    <section className="flex flex-col rounded-none max-w-[573px]">
      <div className="flex flex-col px-7 py-8 w-full rounded-2xl border border-solid shadow-lg bg-zinc-800 border-white border-opacity-30 max-md:px-5 max-md:max-w-full">
        <BudgetSummary
          {...budgetData}
        />
        <hr className="shrink-0 mt-5 max-w-full h-px border border-solid border-white border-opacity-10 w-[515px] max-md:mr-1" />
        <SpendingBreakdown categories={spendingCategories} />
      </div>
    </section>
  );
};

export default BudgetingDashboard;