/**
 * This code was generated by Builder.io.
 */
"use client"
import React from 'react';


interface BudgetSummaryProps {
  currentCashFlow: number;
  remainingBudget: number;
  spent: number;
  earned: number;
}

const BudgetSummary: React.FC<BudgetSummaryProps> = ({
  currentCashFlow,
  remainingBudget,
  spent,
  earned
}) => {
  return (
    <div className="flex gap-5 max-md:flex-col max-md:mr-1 max-md:max-w-full">
      <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
        <div className="flex flex-col items-start text-base font-bold text-white max-md:mt-8">
          <h2 className="text-xl">This Month's Budgeting</h2>
          <p className="mt-6">Current Cash Flow: ${currentCashFlow}</p>
          <p className="self-stretch mt-2">
            You have ${remainingBudget} left to spend this month to meet your saving goal.
          </p>
        </div>
      </div>
      <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
        <div className="flex flex-col grow mt-11 max-md:mt-10">
          <p className="self-start ml-5 text-base font-bold text-right text-lime-300 max-md:ml-2.5">
            ${spent} spent
          </p>
          <div className="flex flex-col justify-center items-start py-px mt-3 rounded-3xl bg-white bg-opacity-20 max-md:pr-5">
            <div className="flex shrink-0 bg-lime-300 rounded-3xl h-[17px] w-[111px]" />
          </div>
          <p className="self-end mt-1.5 text-base font-bold text-right text-white text-opacity-70">
            ${earned} earned
          </p>
        </div>
      </div>
    </div>
  );
};

export default BudgetSummary;