/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface CategoryIconProps {
  icon: string;
  name: string;
  color: string;
}

const CategoryIcon: React.FC<CategoryIconProps> = ({ icon, name, color }) => {
  return (
    <div className="flex gap-2.5 mt-2.5 whitespace-nowrap max-md:mr-1.5">
      <div className={`px-2 text-base font-bold text-black rounded-3xl ${color} border-solid bg-stone-900 border-[0.5px] h-[30px] w-[30px]`}>
        {icon}
      </div>
      <div className="self-start text-sm text-white">{name}</div>
    </div>
  );
};

export default CategoryIcon;