/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface CategoryProgressProps {
  spent: number;
  budget: number;
  color: string;
}

const CategoryProgress: React.FC<CategoryProgressProps> = ({ spent, budget, color }) => {
  const filledDots = Math.floor((spent / budget) * 8);
  const emptyDots = 8 - filledDots;

  return (
    <div className="flex gap-2.5 items-start mt-6 text-sm text-white max-md:mr-2">
      {[...Array(emptyDots)].map((_, index) => (
        <div key={index} className="flex shrink-0 w-4 h-4 rounded-full bg-white bg-opacity-10" />
      ))}
      {[...Array(filledDots)].map((_, index) => (
        <div key={index + emptyDots} className={`flex shrink-0 w-4 h-4 rounded-full ${color.replace('border-', 'bg-')} fill-${color.replace('border-', '')}`} />
      ))}
      <div className="grow shrink self-stretch w-[155px]">
        ${budget - spent} left in ${budget} budget
      </div>
    </div>
  );
};

export default CategoryProgress;