/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { SpendingCategory } from './types';
import CategoryIcon from './CategoryIcon';
import CategoryProgress from './CategoryProgress';

interface SpendingBreakdownProps {
  categories: SpendingCategory[];
}

const SpendingBreakdown: React.FC<SpendingBreakdownProps> = ({ categories }) => {
  return (
    <div>
      <h3 className="self-start mt-5 text-base font-bold text-white">
        Spending breakdown
      </h3>
      <div className="mt-5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[22%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col w-full max-md:mt-10">
              {categories.map((category, index) => (
                <CategoryIcon key={index} icon={category.icon} name={category.name} color={category.color} />
              ))}
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[78%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col self-stretch my-auto w-full max-md:mt-10">
              {categories.map((category, index) => (
                <CategoryProgress
                  key={index}
                  spent={category.spent}
                  budget={category.budget}
                  color={category.color}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SpendingBreakdown;