/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface LearningTrackerItemProps {
  iconSrc: string;
  title: string;
}

const LearningTrackerItem: React.FC<LearningTrackerItemProps> = ({ iconSrc, title }) => {
  return (
    <div className="flex gap-2.5">
      <img
        loading="lazy"
        src="learned.svg"
        alt={`${title} icon`}
        className="object-contain shrink-0 bg-lime-300 rounded-full aspect-square fill-lime-300 h-[30px] w-[30px]"
      />
      <div className="self-start">{title}</div>
    </div>
  );
};

export default LearningTrackerItem;