/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface ChartBarProps {
  paid: number;
  total: number;
}

const ChartBar: React.FC<ChartBarProps> = ({ paid, total }) => {
  return (
    <div className="relative flex flex-col-reverse items-center w-[39px] h-[200px" style={{ height: `100px` }}>
      <div className="absolute top-0 text-white font-light text-sm -mt-10 transform -rotate-90">
        ${total}k
      </div>
      {/* Grey bar - placed behind */}
      <div
        className="absolute bg-zinc-600 rounded-[30px_30px_0px_0px] w-[39px]"
        style={{ height: '100%' }}
      />

      {/* Green bar - placed in front */}
      <div
        className="relative bg-lime-300 rounded-[30px_30px_0px_0px] w-[39px] z-10"
        style={{ height: `${(paid / total) * 100}%` }}
      >
        <div className="absolute bottom-1/2 translate-y-1/2 text-black transform -rotate-90
        text-sm font-bold w-full text-center z-20 font-light">
          ${paid}k
        </div>
      </div>

    </div>
  );
};

export default ChartBar;