/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import ChartBar from './ChartBar';

interface items {
  name: string;
  paid: number;
  total: number;
}[];

const itemsData : items[] = [
  { name: "House", paid: 300, total: 500},     // $300k
  { name: "Car Pay", paid: 50, total: 60 },     // $50k
  { name: "Mortgage", paid: 400, total: 1000 },   // $400k
  { name: "Couch", paid: 300, total: 400 }       // $300k
]

const FinancialChart: React.FC<{}> = () => {
  return (
    <section className="flex items-start pt-11 mt-10 pr-4 text-sm leading-none text-center text-white rounded-none">
      <div className="flex flex-auto self-end mt-2 mr-0 whitespace-nowrap">
        <div className="self-end mt-14 mr-0 w-full border border-solid border-white border-opacity-10 min-h-[1px]" />
      </div>
      <div className="flex gap-5 items-start self-start">
        {itemsData.map((item, index) => (
          <div key={index} className="flex flex-col self-stretch">
            <ChartBar paid={item.paid} total={item.total}/>
            <div className="mt-1.5 font-light">{item.name}</div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default FinancialChart;