/**
 * This code was generated by Builder.io
 */
import React from "react";

interface MessageProps {
  message: {
    text: string;
    isUser: boolean;
  };
}

const ChatMessage: React.FC<MessageProps> = ({ message }) => {
  if (message.isUser) {
    return (
      <div className="self-end px-5 pt-3 pb-5 mt-5 max-w-full leading-5 bg-lime-300 rounded-3xl rounded-tr-none w-[250px]">
        {message.text}
      </div>
    );
  }

  return (
    <>
      <div className="flex gap-px items-start mt-2.5 text-xs leading-loose text-white">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/23e558eee9b5993bc0bf589f5e32e745ee0c9dd6cd7ac6ef42fcd41adbf523ca?placeholderIfAbsent=true&apiKey=271c6a8a64c7449c91e4662f85acfb4e"
          alt=""
          className="object-contain shrink-0 aspect-[0.68] w-[15px]"
        />
        <div>Hourglass Advisor</div>
      </div>
      <div className="px-5 pt-3 pb-6 mt-1 max-w-full leading-5 rounded-3xl rounded-tl-none bg-white bg-opacity-80 w-[250px]">
        {message.text}
      </div>
    </>
  );
};

export default ChatMessage;
