/**
 * This code was generated by Builder.io
 */
"use client";
import React, { useState } from "react";
import { Message } from "./FinancialAdvisor";
import { GoogleGenerativeAI, GenerationConfig } from "@google/generative-ai";
import useBudgetStore from "../SpendingDashboard/BudgetStore";

interface ChatInputProps {
  onSendMessage: (message: Message) => void;
}

// Define types for budget data
interface BudgetData {
  currentCashFlow: number;
  remainingBudget: number;
  spent: number;
  earned: number;
}

// Define the structure of the response schema
interface ResponseSchema {
  response: string;
  updated: BudgetData;
}


const generationConfig : any = {
  temperature: 0.5,
  topP: 0.95,
  topK: 40,
  maxOutputTokens: 8192,
  responseMimeType: "application/json",
  responseSchema: {
    type: "object",
    properties: {
      response: {
        type: "string"
      },
      updated: {
        type: "object",
        properties: {
          currentCashFlow: {
            type: "number"
          },
          remainingBudget: {
            type: "number"
          },
          spent: {
            type: "number"
          },
          earned: {
            type: "number"
          }
        }
      }
    }
  },
};

if (!process.env.NEXT_PUBLIC_GEMINI_API_KEY) throw Error("No valid API key.");
const genAI = new GoogleGenerativeAI(process.env.NEXT_PUBLIC_GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

const chatSession = model.startChat({
  generationConfig,
  history: [
    {
      role: "user",
      parts: [
        {text: "Could you help me update my budget setting to have extra $200 every month? here is my current budget info: budgetData: {\n    currentCashFlow: 5000,\n    remainingBudget: 2000,\n    spent: 1500,\n    earned: 3000,\n  }"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1800, \"spent\": 1500}}\n\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "Could you help me update my budget setting to have extra $500 every month? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "Sure, let's increase the amount you need to save every month by $500 to reach your goal. I have made the changes in you dashboard.\n```json\n{\"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1500, \"spent\": 1500}}\n\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "Could you help me update my budget setting to have extra $200 every month? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "Sure, let's increase the amount you need to save every month by $200 to reach your goal. I have made the changes in you dashboard.\n```json\n{\"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1800, \"spent\": 1500}}\n\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "Could you help me update my budget setting to have extra $200 every month? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "Sure, let's increase the amount you need to save every month by $200 to reach your goal. I have made the changes in you dashboard.\n```json\n{\"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1800, \"spent\": 1500}}\n\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "Could you help me update my budget setting to have extra $200 every month? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"response\": \"Sure, let's increase the amount you need to save every month by $200 to reach your goal. I have made the changes in you dashboard.\",\n\"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1800, \"spent\": 1500}}\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "Could you help me update my budget setting to have extra $200 every month? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"response\": \"Sure, let's increase the amount you need to save every month by $200 to reach your goal. I have made the changes in you dashboard.\", \"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1800, \"spent\": 1500}}\n\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "Could you help me update my budget setting to have extra $500 every month? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"response\": \"Sure, let's increase the amount you need to save every month by $500 to reach your goal. I have made the changes in you dashboard.\", \"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1500, \"spent\": 1500}}\n\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "I have earned $500 extra this month, should I add this to my saving goal?"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"response\": \"Good to hear! I'd suggest to add this to your earned amount for now, and adjust budgetting next month accordingly. I have updated your dashboard.\",\n\"updated\": {\"currentCashFlow\": 5000, \"earned\": 3500, \"remainingBudget\": 2500, \"spent\": 1500}}\n\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "I have earned $500 extra this month, should I add this to my saving goal?"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"response\": \"Good to hear! I'd suggest to add this to your earned amount for now, and adjust budgetting next month accordingly. I have updated your dashboard.\", \"updated\": {\"currentCashFlow\": 5000, \"earned\": 3500, \"remainingBudget\": 2500, \"spent\": 1500}}\n\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "How can I start saving for a down payment for a house? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"response\": \"We can increase the amount you need to save per month by $200. I have made the change. You should see it reflected on your dashboard.\", \"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1800, \"spent\": 1500}}\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "How can I start saving for a down payment for a house? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"response\": \"We can increase the amount you need to save per month by $200. I have made the change. You should see it reflected on your dashboard.\", \"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1800, \"spent\": 1500}}\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "How can I start saving for a down payment for a house? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"response\": \"We can increase the amount you need to save per month by $200. I have made the change. You should see it reflected on your dashboard.\", \"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1800, \"spent\": 1500}}\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "How can I start saving for a down payment for a house? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"response\": \"That's a great goal!  Let's figure out a plan to save for a down payment.  Saving $200 more per month should help you to reach the goal. I have updated your dashboard for you.\", \"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1800, \"spent\": 1500}}\n\n```"},
      ],
    },
    {
      role: "user",
      parts: [
        {text: "How can I start saving for a down payment for a house? here is my current budget info: budgetData: {\ncurrentCashFlow: 5000,\nremainingBudget: 2000,\nspent: 1500,\nearned: 3000,\n}"},
      ],
    },
    {
      role: "model",
      parts: [
        {text: "```json\n{\"response\": \"That's a great goal!  Let's figure out a plan to save for a down payment.  Saving $200 more per month should help you to reach the goal. I have updated your dashboard for you.\", \"updated\": {\"currentCashFlow\": 5000, \"earned\": 3000, \"remainingBudget\": 1800, \"spent\": 1500}}\n\n```"},
      ],
    },
  ],
});

const ChatInput: React.FC<ChatInputProps> = ({onSendMessage}) => {
  const budgetData = useBudgetStore((state) => state.budgetData);
  const updateBudgetData = useBudgetStore((state) => state.updateBudgetData);

  const [inputText, setInputText] = useState("");

  // Function to handle input changes
  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setInputText(event.target.value);
  };

  // Function to handle form submission and make the API call
  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();

    const userPrompt : Message = {
      text: inputText,
      isUser: true,
    }

    if (inputText.trim()) {
      onSendMessage(userPrompt);
      setInputText("");
    }

    try {
      const prompt = userPrompt.text + ". Here are my current budget: "+ JSON.stringify(budgetData);

      // const result = await model.generateContent(prompt);
      const result = await chatSession.sendMessage(prompt);

      const responseText = result.response.text();
      // const responseData = result.updated;
      console.log(responseText);
      // console.log(responseData)
      const responseJSON : ResponseSchema = JSON.parse(result.response.text()) as ResponseSchema;

      if (responseJSON?.response?.trim()) {
        onSendMessage({
          text: responseJSON.response.trim(),
          isUser: false,
        });
      }

      if(responseJSON?.updated){
        console.log("updating data: "+JSON.stringify(responseJSON.updated));
        updateBudgetData(responseJSON.updated);
      }

    } catch (error) {
      console.error("Error making API call:", error);
    }
  };

  return (
    <form className="self-stretch mt-8 mb-8 mx-5 flex-end" onSubmit={handleSubmit}>
      <label htmlFor="chatInput" className="sr-only">
        Write a message
      </label>
      <input
        id="chatInput"
        type="text"
        className="px-5 pt-3 pb-5 w-full text-base bg-white bg-opacity-20 rounded-[50px] text-white text-opacity-50"
        placeholder="Write a message..."
        aria-label="Write a message"
        value={inputText}
        onChange={handleInputChange}
      />
    </form>
  );
};

export default ChatInput;
