/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { AccountRow } from './AccountRow';

type AccountData = {
  category: string;
  accounts: {
    name: string;
    balance: string;
  }[];
};

const accountData: AccountData[] = [
  {
    category: 'Checking',
    accounts: [{ name: 'Bank of America...0004', balance: '$600.00' }]
  },
  {
    category: 'Savings',
    accounts: [{ name: 'Bank of America...0002', balance: '$3000.00' }]
  },
  {
    category: 'Credit',
    accounts: [
      { name: 'Bank of America...0003', balance: '-$500.00' },
      { name: 'Saphire Reserve...0005', balance: '-$500.00' }
    ]
  }
];

export const AccountSummary: React.FC = () => {
  return (
    <section className="flex flex-col gap-1 text-sm text-white rounded-none max-w-[267px] mt-3">
      {accountData.map((category, index) => (
        <div key={index}>
          <h2 className="text-base font-bold text-lime-300 mb-1">
            {category.category}
          </h2>
          {category.accounts.map((account, accountIndex) => (
            <AccountRow
              key={`${category.category}-${accountIndex}`}
              name={account.name}
              balance={account.balance}
            />
          ))}
        </div>
      ))}
    </section>
  );
};