/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface SpendingCategoryProps {
  emoji: string;
  category: string;
  borderColor: string;
  amount: number;
  budget: number;
  color: string;
}

const SpendingCategory: React.FC<SpendingCategoryProps> = ({
  emoji,
  category,
  borderColor,
  amount,
  budget,
  color
}) => {
  const filledCircles = Math.floor((amount / budget) * 8);
  const emptyCircles = 8 - filledCircles;

  return (
    <div className="flex items-center justify-between mt-2.5 whitespace-nowrap max-md:mr-1.5">
      <div className="flex items-center gap-2.5">
        <div className={`px-2 text-base font-bold text-black rounded-3xl ${borderColor} border-solid bg-stone-900 border-[0.5px] h-[30px] w-[30px] flex items-center justify-center`}>
          {emoji}
        </div>
        <div className="text-sm text-white">
          {category}
        </div>
      </div>
      <div className="flex items-center gap-2.5">
        {[...Array(emptyCircles)].map((_, index) => (
          <div key={`empty-${index}`} className="flex shrink-0 w-4 h-4 rounded-full bg-white bg-opacity-10" />
        ))}
        {[...Array(filledCircles)].map((_, index) => (
          <div key={`filled-${index}`} className={`flex shrink-0 w-4 h-4 ${color} rounded-full`} />
        ))}
      </div>
      <div className="text-sm text-white w-[155px] text-right">
        ${amount} left in ${budget} budget
      </div>
    </div>
  );
};

export default SpendingCategory;