/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface AssetLabelProps {
  assetName: string;
}

const AssetLabel: React.FC<AssetLabelProps> = ({ assetName }) => {
  return (
    <div className="flex gap-5 justify-between max-w-full text-sm leading-none text-lime-300 whitespace-nowrap w-[116px]">
      <h2 className="self-start">{assetName}</h2>
      <div className="shrink-0 w-px border border-white border-dashed h-[139px]" />
    </div>
  );
};

export default AssetLabel;