/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import AssetLabel from './AssetLabel';
import Chart from './Chart';
import TimelineLabels from './TimelineLabels';

interface AssetChartProps {
  assetName: string;
  chartImageSrc: string;
}

const AssetChart: React.FC<AssetChartProps> = ({ assetName, chartImageSrc }) => {
  return (
    <section className="flex flex-col max-w-[273px] mt-5">
      {/* <AssetLabel assetName={assetName} /> */}
      <Chart imageSrc="projection.svg" />
      {/* <hr className="shrink-0 w-full h-px border border-solid border-white border-opacity-10" /> */}
      {/* <TimelineLabels /> */}
    </section>
  );
};

export default AssetChart;