/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const TimelineLabels: React.FC = () => {
  const labels = [
    { text: '0', className: '' },
    { text: 'Today', className: 'text-center' },
    { text: '10 yr', className: 'text-right' }
  ];

  return (
    <div className="flex gap-5 justify-between mt-1.5 w-full text-xs leading-none text-white">
      {labels.map((label, index) => (
        <div key={index} className={label.className}>{label.text}</div>
      ))}
    </div>
  );
};

export default TimelineLabels;